Customer Facade added
VegasDevApp/JB_Project pull request #30
Opened 2024-03-02 21:25 UTC by R123NLL

2024-03-03 16:24 UTC, VegasDevApp requested changes
Оставил замечания.
Часть методов дао я сделал в AdminFacade посмотри если можно что-то взять от туда

2024-03-03 16:24 UTC, VegasDevApp commented on src/cls/coupon/dao/impl/CouponsDaoImpl.java
> +        String sql = "SELECT * FROM COUPONS WHERE ID=?";
Тут SQL запрос по Coupon ID, а ты передаешь Customer ID.
Результат будет, что он вернет 1 или NULL, 1 в случае если Coupon ID совпадет с Customer ID.

2024-03-03 16:24 UTC, VegasDevApp commented on src/cls/coupon/dao/impl/CouponsDaoImpl.java
> +        String sql = "SELECT * FROM COUPONS WHERE ID=?";
Тут SQL запрос по Coupon ID, а ты передаешь Category ID.
Результат будет, что он вернет 1 или NULL, 1 в случае если Coupon ID совпадет с Category ID.

2024-03-03 16:24 UTC, VegasDevApp commented on src/cls/coupon/dao/impl/CouponsDaoImpl.java
> +        String sql = "SELECT * FROM COUPONS WHERE ID=? AND PRICE <= ?";
Тут SQL запрос по Coupon ID, а ты передаешь Customer ID.
Результат будет, что он вернет 1 или NULL, 1 в случае если Coupon ID совпадет с Customer ID.

2024-03-03 16:24 UTC, VegasDevApp commented on src/cls/enums/Category.java
>          return categories[0];
проверь что количество элементов в  Category.values() меньше или равно значению id
если нормально то верни 
`return categories[id-1];`

цикл не нужен

2024-03-03 16:24 UTC, VegasDevApp commented on src/cls/facade/customer/CustomerFacade.java
> +    private int customerID;
Посмотри как у меня (AdminFacade) сделан логин.
В группе ватсап, я оставил видео, как я это сделал.

Тут получается, что можно создать экземпляр класса передав ему любой индефикатор.

2024-03-03 16:24 UTC, VegasDevApp commented on src/cls/facade/customer/CustomerFacade.java
> +                return customerByEmail.getPassword().equals(password);
если совпало, то присоединить ID кастомера в приватную переменную на 11 линии

2024-03-03 18:20 UTC, R123NLL commented on src/cls/facade/customer/CustomerFacade.java
> +                return customerByEmail.getPassword().equals(password);
![image](https://github.com/VegasDevApp/JB_Project/assets/142436363/9735da17-6d92-43ab-b581-a0aced055d59)

2024-03-03 18:31 UTC, R123NLL commented on src/cls/facade/customer/CustomerFacade.java
> +    private int customerID;
![image](https://github.com/VegasDevApp/JB_Project/assets/142436363/1ce1d930-e2b5-4bc3-9367-f7622479b478)

2024-03-04 08:35 UTC, R123NLL commented on src/cls/facade/customer/CustomerFacade.java
> +                return customerByEmail.getPassword().equals(password);
![image](https://github.com/VegasDevApp/JB_Project/assets/142436363/d34a13d7-2bb2-47bd-8e9d-62b6968ce0a6)


i made it better

2024-03-06 05:04 UTC, VegasDevApp requested changes

2024-03-06 05:04 UTC, VegasDevApp commented on src/cls/facade/CustomerFacade.java
> +    private boolean isLoggedIn = false;
Тебе private boolean isLoggedIn = false; не нужен
я его как пример привел, тебе нужно заполнять customerID; из логина, как ты сделал.

2024-03-06 05:04 UTC, VegasDevApp commented on src/cls/facade/CustomerFacade.java
> +        if (!this.isLoggedIn) {
здесь надо проверить, чтоб customerID был больше 0

2024-03-06 05:04 UTC, VegasDevApp commented on src/cls/facade/CustomerFacade.java
> +            throw new Exception("Access denied, please log in first!");
возьми новые изменения из main там новый пакедж exceptions  так есть новый exception - используй его

2024-03-06 22:12 UTC, merged